import { type NextPage } from "next";
import Head from "next/head";

import { useState } from "react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const { mutate } = api.youtube.youtube.useMutation();
  const [input, setInput] = useState({ alias: "", topic: "" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        className="border border-black"
        placeholder="Input Alias"
        type="text"
        value={input.alias}
        onChange={(e) =>
          setInput((prev) => ({ ...prev, alias: e.target.value }))
        }
      />
      <input
        className="border border-black"
        placeholder="Input Topic"
        type="text"
        value={input.topic}
        onChange={(e) =>
          setInput((prev) => ({ ...prev, topic: e.target.value }))
        }
      />
      <button
        type="button"
        onClick={() => {
          mutate({ topic: input.topic, alias: "@" + input.alias });
        }}
      >
        Go
      </button>
    </>
  );
};

export default Home;
